name: Build Static Libs x64

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    # --- LINUX DEPENDENCIES ---
    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libgtk-3-dev libwebkit2gtk-4.1-dev

    # --- MACOS DEPENDENCIES ---
    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

    # --- WINDOWS DEPENDENCIES ---
    - name: Install Dependencies (Windows)
      if: runner.os == 'Windows'
      run: choco install doxygen.install graphviz

    # --- CMAKE CONFIG ---
    - name: Configure CMake
      run: |
        COMMON_FLAGS="-DBUILD_SHARED_LIBS=OFF -DWEBVIEW_BUILD_DOCS=OFF"

        if [ "$RUNNER_OS" == "macOS" ]; then
          cmake -S . -B build -DCMAKE_OSX_ARCHITECTURES=x86_64 $COMMON_FLAGS
        elif [ "$RUNNER_OS" == "Windows" ]; then
          cmake -S . -B build -G "MinGW Makefiles" $COMMON_FLAGS
        else
          cmake -S . -B build $COMMON_FLAGS
        fi
      shell: bash

    # --- FIX AND BUILD (ИСПРАВЛЕНО ЗДЕСЬ) ---
    - name: Build
      # Создаем папку вручную, так как скрипт сборки забывает это сделать и падает
      run: |
        cmake -E make_directory build/core/amalgamation
        cmake --build build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libwebview-${{ matrix.os }}-x64
        path: |
          build/**/*.a
          build/**/*.lib
